### ISSUE TITLE
Lantern Website - Lantern Logo shows up as lines in the browser tab when navigated to the blog page

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2300]
![blog page](https://cloud.githubusercontent.com/assets/11394369/6621432/9c476538-c8fc-11e4-9a46-ab7010b2a656.png)

**Comment by atavism** [comment]
This should also be fixed now @sheena3

**Comment by sheena3** [comment]
Still the same. Marked in red circle.

![still the lines are displayed instead of lantern logo](https://cloud.githubusercontent.com/assets/11394369/6986864/268b9ea8-da5f-11e4-8eb1-17a1df914820.png)
